#+title: 敢不敢做个复杂的人

3.信任和道德

就在前几天，我看到一个英国的调查，让老百姓评选心目中哪种职业的人最值得信任。结果是这样的 ——

排名最高的是护士，有94%的英国人信任护士。往下依次是医生、教师、教授、科学家、法官、天气预报员、警察、电视新闻朗读者、牧师、律师、民意测验调查员、银行家、记者，以及排名最后的是政客，信任度只有17%。

我认为这个排名反映的不是道德问题。个人和个人可能有道德差异，你总不能说一个行业的人道德都有问题吧。我认为这个排名反映的是“复杂度”问题。

这个行业处理的事务越复杂，别人就越觉得这个行业的人不可信任。为什么医生的可信度不如护士？因为护士按流程做事就行，而医生得作更复杂的判断。科学家研究的问题很难，但是人际关系简单。警察和律师经常面临各种各样的挑战和选择，他们的工作其实更复杂。记者观察社会，政客作出决策，他们不管怎么做都有理，也不管怎么做都没理，他们的工作最复杂。

如果你做的是简单的事儿，你的三观就可以简单。你完全可以享受岁月静好，相信好人应该有好报，追追娱乐明星，对某些政客表示崇拜，同时对某些政客表示鄙视。

可如果你做的是复杂的事儿，你的三观就得变复杂。你得认识到世界上的事儿并没有一定之规。民主党鼓吹的爱心有道理，共和党让穷人自立自强也有道理。你会注意到被人崇拜的政客和被人鄙视的政客可能私下还是朋友关系。

复杂的人有时候得做一些别人不理解、甚至他们自己都不理解的选择 —— 所以别人才觉得他们不可信任。

那你敢不敢，做个复杂的人。

我觉得这个世界的规律是复杂的人使用说服力说服简单的人。

-----
4.简单和复杂

所谓个人成长，有些是知识和技能的完善，有些是性格的磨炼，但我觉得还有一个维度，叫做“变复杂”。

流程是简单的，权力是复杂的。 你得从按照规定流程做事，变成独立自主，根据自己的判断做事，甚至根据自己的判断让别人做事。

原则性是简单的，灵活性是复杂的。 理念都是好理念，原则都是好原则，但是面对一件具体的事情，各种原则和理念往往互相冲突，你能不能灵活处理。

价值观是简单的，大目标是复杂的。 “不忘初心”是件很难的事，占领道德制高点最容易，大事业都是各种妥协和取舍的结果。

理论模型是简单的，真实世界是复杂的。 三流知识分子眼里只有价值观和道德制高点，二流知识分子眼里有理论模型，只有第一流的知识分子才知道真实世界比理论模型复杂得多。

讨好观众是简单的，把事做成是复杂的。 奥巴马这样的政客喜欢讨好观众，凡事自己要留个清白，所以他们就不敢承担责任，他们为了不做坏事，就干脆不做事。其实但凡做成了大事的人，哪有不被人骂的。

小人物是简单的，大人物是复杂的。 不管我们怎么包装，“说服力”的本质，是使用各种手段让别人按照你的意志行动 —— 是让别人听你的。说服力的能力越大，你要承担的责任就越大。

说服力，是一个武器。是武器就不能滥用。

如果你太过纠结于说服力道德不道德，你不适合使用说服力。如果你完全不纠结道德问题，觉得只要这个手段能赚钱拿来就用，你也不适合使用说服力。只有当你理解了世界的复杂性，宁可承担责任，知道如何*谨慎*使用说服力的时候，你才真正适合使用说服力。

最后，专业技能都是简单的，精英日课是复杂的。我们总是讲些互相矛盾的道理，因为我们明白，真实世界本来就充满矛盾，而我们想要变复杂。
