#+title: 厉害的CEO是什么样的？

快速决断的能力。

#+BEGIN_QUOTE
遇到任何问题，你要尽可能早、尽可能快地做出决策，而且还必须非常坚定。哪怕是当前的局面还不明朗，信息还不完全，甚至这个领域对你来说很陌生，作为CEO，你仍然需要快速拍板。你拍板了，公司才能行动。

有一个CEO说，“只要有65%的把握，我就会做出决定。”谁都不可能拥有完美的信息，如果什么事情能有百分之百的把握，那何必还要你这个CEO来决定？

这个哲学是错误的决定也比没有决定要好得多。犹豫不决是最糟糕的做法。如果CEO犹豫不决，全公司上下就会陷入不知道做什么的境地，就没有行动力，就可能错失良机。

那你可能说，万一决定错了怎么办？别担心。绝大部分错误都算不了什么，行动是可以随时调整的。

研究者发现，人们在评价CEO的时候，凡是公认的好CEO，都是能快速决策的CEO。只有6%的CEO是因为做出了错误决定而获得了很低的评价，绝大多数CEO是因为决策太慢而被批评。在被撤职的CEO中，只有1/3的人是因为做出了错误决定，大多数人被撤职是因为他们在该做决定的时候没有做决定。

那么，在做决定这件事上，一个聪明人可能就不如那些有决断力的人。聪明人考虑的因素往往过多，瞻前顾后。的确，最后聪明人的决策往往更正确，但是错过时机是更大的罪过。

但决策只是做事的第一步，你有了决定，还得有能耐让别人支持你的决定。
#+END_QUOTE

找到人支持你的决策

#+BEGIN_QUOTE
有位CEO，每当重大决定的时候，都会画一个人物关系图，图中标出了办成这件事情需要涉及到的所有重要人员。然后他会和这些人挨个谈话，取得他们对这个决定的支持。如果有人始终反对他的决定，那么他就会尽力把这个反对的力量往正面的方向引导。

如果别人不支持你，你的“政令”就出不了办公室。所以好的CEO一定要能够将自己的理念传达给董事会以及员工，取得众人的理解和支持，让别人和你站在同一条战线上。这也是为什么CEO要经常向高层汇报工作，有什么成绩得经常说，用成绩证明自己确实值得信任。
#+END_QUOTE

从长远角度出发思考问题和制定策略

#+BEGIN_QUOTE
当市场环境快速变化的时候， CEO应该积极领着公司做出相应的改变，比如推出新产品、公司转型等等，这是CEO最重要的职责之一。

想要做到这一点，CEO必须能够从长远考虑问题。我们可以把公司所有问题分为三类：短期，中期和长远 —— 那么这个研究发现，不行的CEO会花30%的时间去考虑长远问题，而厉害的CEO会花50%的时间去考虑长远问题。这就是说，CEO应该把大部分时间用在考虑公司的长期战略上，而不应该把太多精力花在日常公司管理和运营方面。

如果你心里有一个非常明确的长期战略，你看问题的眼光就不一样了。从战略视角去看，你会获得见微知著的能力！你会从自己的社交圈里，从各个地方取得信息，大大提高敏感度。可能别人没觉得这个事有多重要，可是你一眼就能发现其中可能蕴含着市场即将发生的重大变化！这样你就会抢先一步对公司做出相应的调整。
#+END_QUOTE


给人“可靠感”

#+BEGIN_QUOTE
想要当一个受人肯定的CEO，你必须给人一种“可靠感”。这有两层意思。

第一，你得给人一个合理的预期。这也就是说你计划要干什么事，公司业绩在几个月或者一年内能达到什么程度，你要提前告诉股东和员工，让人觉得你“有谱”。

第二，到了时候，你得达到、最好能超出这个预期，让人觉得你“靠谱”。我觉得这个文化有点受到财务报表制度的影响。上市公司每个季度都要发布一次财报，你得总结这个季度做到了什么，还得汇报下季度想做到什么。华尔街对报表非常敏感，给每个公司一个预期，一旦达不到预期，股价就会受到惩罚。
这是一个非常束缚人的文化，CEO必须时刻确保公司业绩达到预期。在这种情况下，一个发挥稳定、每次都能让公司业绩比华尔街预期稍微好一点的CEO，就非常可贵了
#+END_QUOTE
