#!/usr/bin/env python
# coding:utf-8
# Copyright (C) dirlt

podcasts_tags = [u'Business Disciplines', u'Business', u'Featured FM', u'Business Education', u'Education',
                 u'Accounting Education', u'Thecpaguide', u'Life', u'Marketing', u'Big4accountingfirms', u'Cmaexam',
                 u'Aicpa', u'Cpaguidepodcast', u'Trading', u'Cpaexam', u'Higher Education', u'Business News',
                 u'Achieve', u'Careers', u'Quality', u'Tech', u'Science', u'Podcasting', u'Comedy', u'News',
                 u'Health and Well Being', u'Exercise', u'Activities', u'Religion', u'Muscle', u'Church', u'Fitness',
                 u'Society', u'Alternative Spirituality', u'Christianity', u'Lifestyle', u'Active', u'Curse', u'Chills',
                 u'Cursed', u'|', u'Accounting', u'Accountability', u'Accountant', u'Coach', u'Coaching', u'Finance',
                 u'Intuit', u'Cpa', u'Discipline', u'Alcatrezshow', u'Freestyle', u'Entertainment', u'TV',
                 u'Electronic', u'Star', u'Fleshwound', u'Amateurnight', u'Fortuna', u'Dontgointhehouse', u'Music',
                 u'Sci Fi', u'Setmix', u'Max Brand', u'Stonecold', u'Books', u'Alcatrezradio', u'Jayalva', u'Arts',
                 u'Mlw', u'Wave', u'Psoriasis', u'Chiropractic', u'Health', u'80s', u'New', u'Alternative Health',
                 u'Wellness', u'Natural', u'Punk', u'Eczema', u'Medicine', u'Meditation', u'Holistic Health',
                 u'Nutrition', u'Diet', u'Alternative', u'Aging', u'Encinitas', u'Microcurrent', u'Vitamins',
                 u'Gardening', u'Farming', u'Agribusiness', u'Industries', u'Agcareers', u'Food', u'Feed', u'Livestock',
                 u'Kanban', u'Sports', u'Lean', u'Scrum', u'Software Development', u'Software', u'Development',
                 u'Agility', u'Programming', u'Product', u'Less', u'Training', u'Safe', u'Owner', u'Master', u'Divorce',
                 u'Conversations', u'Ptsd', u'Life After Divorce', u'Divorce Recovery', u'Family of A Vet', u'Tbi',
                 u'40k', u'Afterlife', u'African', u'Black', u'American', u'African American', u'Politics', u'Movies',
                 u'Communities', u'Diversity', u'Race', u'Diaspora', u'History', u'Reformed', u'Africa', u'Culture',
                 u'People', u'Films', u'Society & Culture', u'', u'Guitar Student', u'Live', u'Folk', u'Fingerstyle',
                 u'Guitar', u'Songwriter', u'Theater', u'Worldmusic', u'Guitar Lessons', u'Itsafrogslife',
                 u'Guitar Course', u'Electric', u'Liverpool', u'Lovetolisten', u'Rocklin', u'Sda', u'Sermon', u'Bible',
                 u'Christian', u'Seventh', u'Seventh Day Adventist', u'Day', u'Listener', u'Source', u'Gracepoint',
                 u'God', u'Christ', u'Social Sciences', u'Catholic', u'Paranormal', u'Spiritual Beings',
                 u'Spirituality', u'"isha', u'Philosophy', u'Foundation"', u'Sadhguru', u"Alzheimer's Disease",
                 u'Alzheimers', u'Kids and Family', u'Disease', u'Mental Health', u'US Government', u'Caregiving',
                 u'Dementia', u'Parkinsonsdisease', u'Caregiver', u'Alzheimersdisease', u'Family', u'Nfl',
                 u'American Football', u'Fantasy American Football', u'Fantasy Sports', u'Fantasy', u'Fantasy Football',
                 u'Football', u'Mmqb', u'Klemko', u'Benoit', u'College', u'Themmqb', u'Sports News', u'UK',
                 u'Fantasyfootball', u'Rankings', u'ghost Stories', u'Television', u'Horror', u'Story', u'Fine Arts',
                 u'American Horror Story', u'Current TV', u'Fx', u'Ebooks', u'Free Audio Books', u'Audio Books',
                 u'Loyalbooks.com', u'Loyal Books', u'Empire', u'Audiobook', u'Idol', u'American Idol',
                 u'Blogtalkradio', u'Singing', u'Pop Culture', u'Reality', u'Physiology', u'Amazing',
                 u'Anatomy Education', u'Medical', u'Survivor', u'Grey', u'Jlg', u'Science Education', u'Lecture',
                 u'Anatomy', u'Exercisescience', u"Grey's Anatomy", u'S', u'Afem', u'Vertebrate', u'Massage',
                 u'Biology', u'Doctor', u'Healing', u'Prosperity', u'Archangels', u'Evolution', u'Angelinvestor', u'Vc',
                 u'Atlantis', u'Startups', u'Mediumship', u'Interview', u'Entrepreneur', u'Anglocatholic', u'Trinity',
                 u'Acna', u'Holy', u'Theology', u'Jesus', u'Grace', u'Evangelical', u'Sermons', u'Anglicanism',
                 u'Apologetics', u'Truth', u'Mobile', u'Operating Systems', u'Technology', u'Google', u'Apps', u'Twit',
                 u'Smart Phones', u'Mobile Phones', u'Smartphones', u'Android Os', u'Androiddev', u'Appstore',
                 u'Developer', u'Gadgets', u'Phone', u'Tablets', u'Tablet', u'Smartphone', u'Vegan', u'Animal Rights',
                 u'Rights', u'Veganism', u'Animal', u'Animals', u'Animals and Pets', u'Vegetarian', u'Animal Welfare',
                 u'Environment', u'Vegetarianism', u'Pets', u'Anime', u'Birds', u'Cats', u'Puppies', u'Animal Lovers',
                 u'Cat', u'Puppy', u'Dogs', u'Pet Life Radio', u'Dog', u'Pet', u'Pet Care', u'Celebrities', u'Manga',
                 u'Hobbies', u'the Simpsons', u'Japan', u'Cinema', u'Disney', u'Travel', u'Animated Fiction', u'Batman',
                 u'Animation', u'Sailormoon', u'Otaku', u'Cartoons', u'Physics', u'Astronomy', u'Paleontology',
                 u'Anthropology Education', u'Archaeology', u'Archeology', u'Nova', u'Nature', u'Discovery', u'Math',
                 u'Mathematics', u'Earth', u'Disasters', u'Pbs', u'Lockett', u'Tcu', u'Ethnomusicology',
                 u'Ethnographic', u'Racism', u'Anthropology', u'Nebraska', u'Plains', u'Ethnography',
                 u'App Business Education', u'IT Industry', u'Web', u'Gatekeeper', u'App', u'Apple', u'Tech Education',
                 u'Games', u'App Business', u'End', u'Ios', u'Store', u'React', u'Ipad', u'Watch', u'Javascript',
                 u'Mac', u'Ipod', u'Iphone', u'Appletv', u'Sdk', u'Applewatch', u'Macintosh', u'Xcode', u'Keynote',
                 u'Presentation', u'Osx', u'Video', u'360', u'Arcade', u'Retro', u'Pinball', u'Nintendo', u'Gaming',
                 u'Xbox', u'Video Games', u'Game', u'Classic', u'Videogames', u'Retro Gaming', u'Playstation', u'Sega',
                 u'Atari', u'Archaeology Education', u'Crmarch', u'Humanities Education', u'Archaeological', u'Digital',
                 u'Crm', u'Humanities', u'Stories', u'Natural Sciences', u'Prehistory', u'Usmodernist', u'Schindler',
                 u'Ncmh', u'Modernist', u'Graphic Design', u'Architect', u'Art', u'Design', u'Neutra', u'Lautner',
                 u'Architects', u'Building', u'Architecture Education', u'Wright', u'Construction', u'Prints',
                 u'Drawing', u'Sculpture', u'Architecture', u'Painting', u'Exhibition', u'Philadelphia Museum of Art',
                 u'Photography', u'Cultural Events', u'Pentecostal', u'Preaching', u'Upci', u'Cornerstone',
                 u'Deliverance', u'Upc', u'Salvation', u'Pastor', u'Religion & Spirituality', u'Teaching', u'Pentecost',
                 u'Holy Ghost', u'DC', u'Cw', u'Superheroes', u'Cassidy', u'Greenarrow', u'Barrowman', u'Oliver',
                 u'Comics', u'Katie', u'Flash', u'Amell', u'Green', u'Green Arrow', u'Wenger', u'Arsenal Football Club',
                 u'Arsenal', u'League', u'Premier', u'Epl', u'Soccer', u'Emirates', u'Highbury', u'Club',
                 u'Premiership', u'USA', u'X-Factor', u'English', u'Factory', u'Ai', u'Artificial', u'Learning',
                 u'Artificialintelligence', u'Machine', u'Transhumanism', u'Singularity', u'Machinelearning',
                 u'Artificial Intelligence', u'Intelligence', u'Data', u'Ml', u'Analytics', u'Networks', u'Deep',
                 u'Museum', u'Artists', u'Film', u'Artist', u'Madison', u'Zvo.\u010ci.ti (so.und.ing) 2010',
                 u'Irena Toma\u017ein', u'Houstonian', u'Radio Art', u'Radiocona', u'Sam Houston State University',
                 u'Bearkats', u'Sound Art', u'Ljubljana', u'Horoscope', u'Huntsville', u'Forecast', u'Zodiac',
                 u'Planets', u'Student Newspaper', u'Horoscopes', u'Find', u'Transits', u'Astrology Readings',
                 u'Audience', u'Stars', u'Ortelee', u'Humor', u'Psychic', u'Astronomy Education', u'Nasa', u'Space',
                 u'Telescope', u'Spaceship Spitzer', u'Sky', u'Cg', u'Infrared Astronomy', u'Ipac', u'Night', u"Nasa's",
                 u'Geology', u'Chemistry', u'Razorbacks', u'Universe', u'Cosmology', u'Astrophysics', u'Arkansas',
                 u'Arkansas Razorbacks', u'Varsity Teams', u'Hogs', u'Basketball', u'92.1', u'Trough',
                 u'Sports & Recreation', u'Fayetteville', u'Hog', u'College & High School', u'Sec', u'Baseball',
                 u'Audio', u'Audio Theater', u'Storytelling', u'Fiction', u'Drama', u'Radiodrama', u'Audiodrama',
                 u'Morning Rush Espn Arkansas Derek Ruscin Tommy Craft Arkansas Razorbacks', u'Scifi', u'Theatre',
                 u'Mystery', u'Nightvale', u'Memphis', u'Adventure', u'Audio Drama', u'Free', u'Literature', u'Book',
                 u'Reviews', u'Novel', u'Audio Book', u'Domain', u'Word', u'Spoken', u'Librivox', u'Zombies', u'Public',
                 u'Fantasy Aussie Rules', u'Aussie Rules', u'Footy', u'Afl', u'Rules', u'Australia', u'Aussie',
                 u'Australian', u'Aussierules', u'Essendon', u'Hawthorn', u'Bombers', u'Dt', u'Supercoach',
                 u'Andrew WoMMAck', u'Andrew Womack', u'True Murder', u'Publishing', u'Books and Writing',
                 u'Serial Murder', u'Scripture', u'True Crime', u'Spiritual', u'Authority', u'Writing', u'Aspergers',
                 u'Support', u'Children', u'Asperger', u'Aba', u'Resources', u'Autism Empowerment', u'Eaton',
                 u'Behavior', u'Research', u'Special Needs', u'Automotive Sales', u'Car Sales', u'Cars', u'Repair',
                 u'Automotive', u'Car', u'Car Talk', u'Racing', u'Tuners', u'Sports Cars', u'Model Cars',
                 u'Automotive Advice', u'Automotive Repair', u'Flying', u'Flight', u'Airline', u'Pilots', u'Airports',
                 u'Airplanes', u'Aircraft', u'Airplane', u'Airlines', u'Pilot', u'Safety', u'Godless', u'Skepticism',
                 u'Agnostic', u'Atheist', u'Secular', u'Nerdy', u'Skeptic', u'Humanism', u'Freethought', u'Freethinker',
                 u'Talk', u'Calvary', u'Mccurrie', u'Fundamental', u'Billy', u'Colorado', u'Aughton',
                 u'Prospect361.com', u'Redraft', u'Professional', u'Mlb', u'Yankees', u'Fantasy Baseball',
                 u'Games and Gambling', u'Rich Wilson', u'Rantala', u'Dillinger', u'Kasputis',
                 u'Fantasy Baseball Information', u'Farley', u'Nba', u'Fantasy Basketball', u'NBA', u'Cbs',
                 u'Athletics', u'Truehoop', u'Basketballanalogy', u'Cba', u'Talkhoops', u'Youth Basketball', u'Los',
                 u'Celtics', u'Lakers', u'Angeles', u'Grandma', u'Kobe', u'Joker', u'Dark Knight', u'Jerry', u'Comic',
                 u'Robin', u'Knight', u'Dark', u'Action', u'Dccomics', u'Nostalgia', u'Geeks', u'Frak',
                 u'Battlestar Galactica', u'Battlestar', u'Galactica', u'Board Games', u'Trek', u'Wars', u'Bsg',
                 u'Lost', u'Star Trek', u'Bedtime Stories', u'Star Wars', u'Fringe', u'Tales', u'Fairytale', u'Kids',
                 u'Bedtime', u'Schools', u'School', u'Coldplay', u'Hammond', u'Musicians', u'Drums', u'Big',
                 u'Recording', u'Music Industry', u'War', u'Rock', u'World', u'Xk', u'Brewing', u'Craft', u'Brew',
                 u'Food and Beverage', u'Malt', u'Craftbeer', u'Ipa', u'Hops', u'Ale', u'Brewery', u'Homebrew', u'Home',
                 u'Homebrewing', u'Selfhelp', u'Human', u'Psychology', u'Peace', u'Bettercallsaul', u'Better Call Saul',
                 u'Leadership', u'Saul', u'Call', u'Better', u'Amc', u'Breakingbad', u'Breaking Bad', u'Bad',
                 u'Saulgoodman', u'Bobodenkirk', u'Breaking', u'Crime', u'Dvmpe', u'Antichrist', u'Prophecy', u'Last',
                 u'Ministry', u'Bible Prophecy', u'Daniel', u'Rapture', u'Days', u'Big Brother', u'Realitytv',
                 u'Bigbrother', u'Brother', u'Reality TV', u'Zingbot', u'Juliechen', u'TV & Film', u'Chenbot',
                 u'Big Brother 11', u'Ghosts', u'Alien', u'Sasquatch', u'Aliens', u'Conspiracy', u'Ufo', u'Yeti',
                 u'Cryptozoology', u'Ghost', u'Ape', u'Monsters', u'Rheumatoid', u'Vce', u'Arthritis',
                 u'Biology Education', u'Mr', u'Craig', u'Rheumatic', u'School Education', u'Arapahoe', u'Elsevier',
                 u'Douch', u'Papapodcasts', u'Biologic', u'Neuroscience', u'Immunology', u'Microbiology',
                 u'Biochemistry', u'Agriculture', u'Cancer', u'Honey', u'Bees', u'Bee', u'Honeybees', u'Loose',
                 u'Organic', u'Chemical', u'Survival', u'Homeimprovement', u'Howto', u'Cooking', u'Diy',
                 u'Homesteading', u'Birdwatching', u'Birding', u'Ornithology', u'Watching', u'Online', u'Insurance',
                 u'Internet', u'Media', u'Mcfc', u'Man', u'City', u'Jays', u'Toronto', u'Toronto Blue Jays',
                 u'Manchester', u'Powerlifting', u'Weightlifting', u'Contest', u'Weight', u'Strength', u'Protein',
                 u'Crossfit', u'Athletic', u'Strongman', u'Physique', u'Characteactors', u'Bhangra', u'Asian Fusion',
                 u'Urban Desi Beats', u'Hindi', u'Desi', u'Indian', u'Scenes', u'Remixes', u'Authors', u'Reading',
                 u'Personal', u'Political Science', u'Psychology Education', u'Interviews', u'Poetry', u'Screenwriting',
                 u'Brooklyn Fights', u'Ny Fights', u'Boxing Interview', u'CoMBAt Sports', u'Wrestling Podcast',
                 u'Team Leftjab', u'Starburst Magazine', u'Starburst', u'Blue Box Podcast', u'De La Hoya',
                 u'New Doctor Who', u'Classic Doctor Who', u'Dr Who', u'F1',
                 u'Starburst Magazine Official Doctor Who Podcast', u'Pharma', u'Biotechnology', u'Robotics',
                 u'Healthcare', u'Innovation', u'Investing', u'Robot', u'Pharmaceutical', u'Science & Medicine',
                 u'Expertise', u'Investments', u'Advanced', u'Shillue', u'Kilmeade', u'Starnes', u'Breaking News',
                 u'Todd', u'Abc News', u'Tom', u'Talk Show', u'Boston', u'Grace Brethren', u'Anabaptist', u'Creekside',
                 u'Ohio', u'Gospel', u'Elkhart', u'Zen', u'Buddhism', u'Dharma', u'Mindfulness', u'Buddha',
                 u'Non Fiction', u'Teachings', u'Awareness', u'Buffy', u'Vampire', u'Slayer', u'Angel', u'Joss',
                 u'Whedon', u'Buffythevampireslayer', u'Buffy the Vampire Slayer', u'Spike', u'Recent TV', u'Gellar',
                 u'Vampires', u'Btvs', u'Joss Whedon', u'Sunnydale', u'Business English', u'Toeic', u'Esl',
                 u'Vocabulary', u'Speaking', u'Listening', u'Work', u'Language', u'Lessons', u'MBA Education', u'MBA',
                 u'Economics', u'Economy', u'Law', u'Human Resources', u'Financial', u'Marketing Education', u'Joclyn',
                 u'Adult', u'Real Estate', u'Real Estate Education', u'Violin', u'Publishing Education', u'Rebecca',
                 u'Ielts', u'Language Learning', u'Efl', u'Learn', u'Study', u'Dead', u'Car Accident', u'Walter',
                 u'White', u'Trends', u'Trend', u'Future Trends', u'Retail', u'Management', u'Gold', u'Business Trends',
                 u'Theheart.org', u'Physician', u'Hospital', u'Inreview', u'Lung', u'Insession', u'Heart',
                 u'Cardiovascular', u'Heart Disease', u'Medical Education', u'Cme', u'Pulmonology', u'Jama',
                 u'Employment', u'Self Help', u'Engineering', u'Freelance', u'Jobs', u'Millennials', u'Jobsearch',
                 u'Self Improvement', u'Gracefm', u'Calvary Castle Rock', u'Pastor Dave Love', u'Abc',
                 u'Calvary Chapel Castle Rock', u'Xt3.com', u'Catechism', u'Wyd2008', u'Xt2', u'Cardinal', u'Bioethics',
                 u'Xtc', u'Wyd08', u'Wyd2011', u'Prolife', u'Priest', u'Homilies', u'Bishop', u'Pope', u'Marriage',
                 u'Faith', u'Catholicism', u'Schmitz', u'Fr', u'Father', u'Mike', u'Vogt', u'Barron', u'Kittens',
                 u'House', u'Kitten', u'Popularscience', u'Chemistry Education', u'Polyatomic', u'Chem', u'Equations',
                 u'Metals', u'Element', u'Ions', u'Acs', u'Aacc', u'Compound', u'Pdl', u'Usnews', u'Minor', u'Nbadl',
                 u'Compliance', u'U', u'Loan Modification', u'Foreclosures', u'Short Sales', u'Timothyferriss',
                 u'Timothyferris', u'Workweek', u'Timferriss', u'Timferris', u'4hour', u'Fourhour', u'Tutorial',
                 u'Stlouiscardinals', u'Chicago', u'Chicago Cubs', u'White Sox', u'Houston Astros', u'Chicagocubs',
                 u'Cubs', u'Blackhawks', u'Bulls', u'Bears', u'Major League Baseball', u'Quadcities', u'Lee',
                 u'Chiropractor', u'Advice', u'Consulting', u'Email', u'Fellowship', u'Christian Apologetics',
                 u'Zacharias', u'Ravi', u'Rzim', u'Reason', u'Orthodox', u'Christian Orthodox', u'Orthodoxy', u'Coptic',
                 u'Greek', u'Russian', u'Csf', u'Youth', u'Christian Students', u'Student', u'Student Ministry',
                 u'Students', u'C.s. Lewis', u'Old', u'Classic Radio', u'Time', u'Detective', u'Suspense', u'Otr',
                 u'Vintage', u'Thriller', u'Classic Sitcoms', u'Classic TV', u'Seinfeld', u'Sitcom', u'Brooks', u'Our',
                 u'90s', u'Early', u'Miss', u'Dragnet', u'Gunsmoke', u'Baa', u'Who', u'60 Second Biographies',
                 u'Classical Music', u'Shows', u'Rhett Mclaughlin', u'Clean Comedy', u'Cbc Radio', u'Cbc', u'Rhett',
                 u'Link', u'News Comedy', u'Lukelacoy', u'Link Neal', u'Comedian Chat', u'Change', u'Climate',
                 u'Climate Change', u'Activism', u'Weather', u'Carbon', u'Co2', u'Soil', u'Global', u'Warming',
                 u'Sustainability', u'Energy', u'Blaxploitation', u'Cult', u'B Movies', u'1987', u'Computing',
                 u'Cloud IT', u'Cloud', u'Virtualization', u'Vmware', u'Cloudcomputing', u'Cloud IT Education',
                 u'Bigdata', u'Azure', u'Security', u'Intel', u'Iaas', u'Paas', u'Openstack', u'Hp Helion',
                 u'Contractors', u'Hp', u'Sbc', u'Help', u'Endurance Sports', u'Ironman', u'Sales', u'Citrix', u'Self',
                 u'Triathlon', u'MMAjunkie', u'MMA', u'Wwe', u'CoMBAt', u'Fight', u'Boxing', u'Pro Wrestling', u'Ufc',
                 u'Psychologist', u'Wcw', u'Steveandlarson', u'Kickboxing', u'Ecw', u'Mature Comedy', u'Dawson',
                 u'Greg', u'Feral Audio', u'Shane', u'Comedian', u'Rogan', u'Kreischer', u'Funny', u'Joey', u'Diaz',
                 u'Standup', u'Youtube', u'Hollywood', u'Comedians', u'Stand', u'Heather Mcdonald',
                 u'Comedian Interviews', u'Up', u'Juicy Scoop', u'Ny', u'Sketch Comedy', u'Malley', u'Katg', u'Chemda',
                 u'Sketch', u'Laugh', u'Girl', u'Improv', u'Keith', u'Tabletop', u'Marvel', u'Superman', u'Comic Books',
                 u'Image', u'Comicbook', u'Graphic', u'Dirtbag', u'Hiking', u'Rockclimbing', u'Mountaineering',
                 u'Snowboarding', u'Outdoors', u'Camping', u'Bouldering', u'Alpine', u'Backpacking', u'Outdoor',
                 u'Community Church', u'Relevant', u'Community', u'Vista', u'Message', u'Worship', u'Geoscience',
                 u'Geophysics', u'Computers', u'Computer Science', u'Cs', u'Computer', u'Constitution', u'Barack Obama',
                 u'Conservatism', u'Rush', u'LiMBAugh', u'Obama', u'Political', u'Current Events', u'Conservation',
                 u'Democrat', u'America', u'Democracy', u'Republican', u'Liberal', u'Conspiracy Theories', u'Theories',
                 u'Occult', u'11', u'Theory', u'Conspiracies', u'Weird', u'Conspiracy Theory', u'Paganism',
                 u'Rachel Brathen', u'Moyers', u'Election', u'Surgery', u'Plasticsurgeon', u'Plastic', u'Dermatology',
                 u'Cosmeticsurgery', u'Breast', u'Restylane', u'Cosmetic', u'Spa', u'Facelift', u'Cosmeticsurgeon',
                 u'Botox', u'Ponyexpress', u'Pipe', u'Implants', u'Tobacco', u'Farm', u'Tuck', u'Smoking',
                 u'Independent', u'Coldones', u'Saloondoors', u'Cowgirls', u'Pipes', u'Whiskey', u'Saloon', u'Stations',
                 u'Arrow', u'Gotham', u'Nbc', u'Marveluniverse', u'Agentsofshield', u'Fox', u'Peggycarter', u'Dcu',
                 u'Xmen', u'Netflix', u'Thor', u'Daredevil', u'Jessicajones', u'Odi', u'Test', u'T20', u'Wolverine',
                 u'Cricinfo Talk', u'Talksport2', u'Cricinfo', u'Crickinfo', u'Switch Hit', u'Icc', u'Cricketers',
                 u'Kevin Pietersen', u'Domestic', u'the Switch Hit Cricket Show', u'Jon',
                 u'Jonathan Harris Bass Boycott', u'Truecrime', u'Unsolved', u'Murder', u'Cold', u'True', u'Killers',
                 u'Serial', u'Journalism', u'Case', u'Line', u'Cruises', u'Caribbean', u'Vacation', u'Cruise', u'Ships',
                 u'Hawaii', u'Holland', u'Getaway', u'Carnival', u'Current Affairs', u'Tyler Br\xfbl\xe9',
                 u'Places & Travel', u'Sichuan', u'Shenzhen', u'Monocle', u'Affairs', u'Hangzhou', u'Currentaffairs',
                 u'Current', u'Monocle Magazine', u'Vampire Diaries', u'Game of Thrones', u'Walking Dead', u'Thrones',
                 u'House of Cards', u'Castle', u'Hbo', u'Ethereum', u'Bitcoin', u'Cryptocurrency', u'Cyber Currency',
                 u'Monero', u'Blockchain', u'Crypto', u'Money', u'Currencies', u'Altcoin', u'Dash', u'Altcoins',
                 u'Anarchy', u'Currency', u'Adam', u'Privacy', u'Mtb', u'Biking', u'Bike', u'Tour', u'France',
                 u'Bicycle', u'Cycle', u'Road', u'Uci', u'Armstrong', u'Cyclist', u'Mountain', u'Wonderwoman',
                 u'Supergirl', u'DC Comics', u'Dceu', u'Writer', u'Daily', u'Sportstalk', u'Dailynews', u'Digest',
                 u'Analysis', u'Aviation', u'Ubuntu', u'Linux', u'Android', u'Nite', u'Geek', u'Merritt', u'Jupiter',
                 u'Persona', u'Soul', u'Dark Souls Ii', u'Bloodborne', u'Dark Souls 2', u'Souls', u'Soulful',
                 u'Underground', u'Dark Souls', u'Dj', u'Js', u'Gnu', u'Nerf', u'Coding', u'Script', u'Xml', u'Toolkit',
                 u'Java', u'Python', u'Performance', u'Wont', u'Jay', u'Statistics', u'Datascience', u'Big Data',
                 u'Data Science', u'R', u'Information Visualization', u'Data Visualization', u'Ibm', u'Love',
                 u'Relationship', u'Seduction', u'Dating Advice', u'Sex', u'Relationships', u'Single', u'Pickup',
                 u'Seduce', u'Relationship Advice', u'Girls', u'Gilmore', u'Relationshipadvice', u'Ex', u'Dds',
                 u'Practicemanagement', u'Dental', u'Dentist', u'Practice', u'Tooth', u'Hygiene', u'Patients', u'Teeth',
                 u'Holistic', u'Rosewood', u'Backstage', u'Troian Bellisario', u'Hot Mess', u'Text Messages',
                 u'Blazinry', u'Shay Mitchell', u'Lucy Hale', u'Thom Fogarty', u'Ashley Benson',
                 u'Desperate Housewives', u'Clues', u'Desperate', u'Housewives', u'Gspn', u'Greys', u'Ravenscraft',
                 u'Cliff', u'Stay', u'Silver', u'Motley', u'Fool', u'Vermont', u'Industry', u'Rv', u'Precious',
                 u'Market', u'Investment', u'Transfernado', u'Agile', u'Containers', u'Open Source', u'Deep Learning',
                 u'DevOps', u'Enterprise', u'Continuousintegration', u'Devsecops', u'Showtime', u'Type1diabetes',
                 u'Speak', u'Walking', u'Michael', u'Type', u'Mellitus', u'Type 1', u'Podcaster', u'Cdc', u'Diabetics',
                 u'Type2diabetes', u'Prediabetes', u'Endocrinology', u'Cne', u'T1d', u'Public Health', u'Ce',
                 u'Digital Marketing', u'Digitalmarketing', u'Branding', u'Socialmedia', u'SEO', u'Content', u'Social',
                 u'Blogging', u'Contentmarketing', u'Discgolf', u'Disc Golf', u'Golf', u'Frisbee', u'Frolf', u'Disc',
                 u'Pdga', u'Smashboxx', u'Sportspsychology', u'Northcarolina', u'Smashboxxtv', u'Theme Parks', u'Walt',
                 u'Magic', u'Florida', u'Disneyland', u'Epcot', u'Orlando', u'Waltdisneyworld', u'Anaheim', u'Wdw',
                 u'Kingdom', u'Pixar', u'Crafts', u'How', u'Do It Yourself', u'Jack of All Trades', u'How To',
                 u'Decorating', u'Instructional Videos', u'How To Do Anything', u'How To Do Everything',
                 u'Educational Videos', u'How Do I', u'Learn How To', u'Online Education', u'Bbc', u'Doctor Who',
                 u'Doctorwho', u'Dalek', u'Cybermen', u'Dr', u'Torchwood', u'Tardis', u'British', u'Raid', u'Ps4',
                 u'Crucible', u'Bungie', u'Dog Training', u'Eliza Dushku', u'Dogtraining', u'Firefly', u'Smith',
                 u'Obedience', u'Stargate', u'Weekly', u'Horrible', u'V', u'Valve', u'Moba', u'DotA', u'Esports',
                 u'Legends', u'Dota2', u'Lol', u'Games & Hobbies', u'Play', u'Hon', u'Heroes', u'Steam',
                 u'Downton Abbey', u'Poldark', u'Downton', u'Masterpiece', u'Endeavour', u'Abbey', u'Wallander',
                 u'Inspector Lewis', u'Wgbh Educational Foundation', u'Wgbh', u'Morse', u'Sherlock', u'Serling',
                 u'Perry', u' Fantasy Stories', u'Masion', u'Rob', u'Zero', u'Hour', u'Sciencefiction', u'Holmes',
                 u'Fictionpodcast', u'Uav', u'Quadcopter', u'Unmanned', u'Fpv', u'Multirotor', u'Faa', u'Uas',
                 u'Quadtalk', u'Ambient', u'Bass', u'Dnb', u'Drum', u'Drum & Bass', u'Drum and Bass', u'Jungle',
                 u'Dubstep', u'D&b', u'Electro', u'Liquid', u'Dance', u'Ragga', u'Breakbeat', u'Mix', u'Rave',
                 u'Documentary', u'FilMMAking', u'FilMMAkers', u'Francesca Lalor', u'Nonfiction',
                 u'Documentary On Newstalk', u'Criticism', u'Radio Station', u'Dungeons and Dragons', u'Dragons',
                 u'Acquisition Inc', u'Acquisitions Incorporated', u'Dungeons', u'Rpg', u'D&d', u'Dd', u'Dnd',
                 u'Dungeonsanddragons', u'Dungeons & Dragons', u'Tabletop Games', u'D', u'Eccomerce', u'E-Commerce',
                 u'E-Commerce Education', u'Etsy', u'Handcraft', u'Crafters', u'Commerce', u'Crafting', u'Crochet',
                 u'Handmade', u'Ebay', u'Diamond', u'Jewelry', u'Hop', u'Indie', u'Jazz', u'Reggae', u'Pop', u'Fg',
                 u'Ekg', u'Leo', u'Macroeconomics', u'Hayek', u'Cornell', u'Habits', u'Teaching Trends', u'Ted',
                 u'Teachers', u'Education Tech', u'Cancer Workshops', u'Cancer Education', u'C',
                 u'Programming Education', u'Minimal', u'Techno', u'Idm', u'Electronica', u'Electronic Music',
                 u'Magnatune', u'Instrumental', u'Electronics', u'Electro Rock', u'Creative Commons', u'Experimental',
                 u'Industrial', u'Experimental Electronic', u'Other', u'Mediacurrent', u'Symphony', u'Php',
                 u'Wordpress', u'Drupalconboston2008', u'Lamp', u'Modules', u'Magento', u'Browsers',
                 u'88fbcb25 4ee3 4b60 A0c1 0d13633501e9', u'Shopify', u'Cms', u'Elvispresley', u'Elvis Presley',
                 u'Chimpanzee', u'Elvis Talk', u'Presley', u'Acetuckerspacetrucker', u'Elvis',
                 u'Twisted South Magazine Zeke Loftin', u'Zeke Loftin Twisted South Magazine', u'Elvis News',
                 u'Maureen Mars Blomgren', u'Twisted South', u'Emergency', u'Energetic', u'Emergency Medicine', u'Em',
                 u'Foamed', u'Foam', u'Freeopenaccessmedicaleducation', u'Emergencymedicine',
                 u'Emergencymedicineresidents', u'Medicalstudentpodcast', u'Iowa', u'Emergencymedicinepodcast',
                 u'Residency', u'Running', u'Endurance', u'Run', u'Cycling', u'Marathon', u'Swimming', u'Electricity',
                 u'Solar', u'Wind', u'Power', u'Shamanism', u'Efficiency', u'Renewable', u'Transportation',
                 u'Deception', u'Engineer', u'Idioms', u'English Pronunciation', u'Pronunciation', u'Accent',
                 u'Reduction', u'GraMMAr', u'Conversation', u'Toefl', u'Learning English', u'English Usage',
                 u'Cambridge Exams', u'Cfe', u'Eflelt', u'Usage', u'GraMMAr and Vocabulary', u'Spoken English',
                 u'Audio Lesson Podcasts', u'Oral Practice',
                 u'Drills and Exercises To Learn English and Practice Correct Usage', u'Posh', u'Divided', u'Geekery',
                 u'Sports and Entertainment', u'Redundancy', u'Ladue', u'Elite', u'Hutton', u'Elite: Dangerous',
                 u'Orbital', u'Bs', u'Dangerous', u'Galnet', u'Drabble', u'Abraka', u'Kissyman', u'Elitedangerous',
                 u'Drabbles', u'Entrepreneur Interviews', u'Entrepreneurship', u'Passiveincome', u'Wookies', u'Startup',
                 u'Entrepreneurs', u'Success', u'Small', u'Solopreneurs', u'Entrepreneur Lifestyle', u'Income',
                 u'Motivation', u'Inspiration', u'Career', u'Daveramsey', u'Solopreneur', u'Lifestyleentrepreneur',
                 u'Millionaire', u'Transactionfraud', u'Mobilesecurity', u'Dr. Ande', u'Iotsecurity', u'Breaches',
                 u'Minority', u'Business Talk Radio', u'Water', u'Iva Radio Network', u'Cybersecurity',
                 u'Buisness Ownership', u'Informationsecurity', u'Environmental', u'China', u'Monoxide', u'Dioxide',
                 u'Gases', u'Dressage', u'Wedding', u'Creation', u'Horse', u'Equine', u'Horses', u'Horsemanship',
                 u'Pony', u'Riding', u'Eventing', u'Horseriding', u'Audio Horse Riding Lessons', u'Jumper', u'Trainer',
                 u'Arena', u'Showjumping', u'Jumping', u'Stables', u'Schooling', u'Brinkley', u'Scrivener', u'Glen',
                 u'Falls', u'Sioux', u'Evangelist', u'Entertainment Industry', u'Showbiz', u'Music Business', u'Cover',
                 u'Musicality', u'Hip', u'Trivia', u'Knowledge', u'Facts and Trivia', u'Quiz', u'Howstuffworks',
                 u'How It Works', u'How Stuff Works', u'Skies', u'Falling', u'Ga', u'Jimmy', u'Random', u'Spielberg',
                 u'Person of Interest', u'Falling Skies', u'Parenting', u'Genealogy', u'Focus', u'Cbssports.com',
                 u'Cbs Sports', u'Rotoballer Radio', u'Dfs', u'Glb', u'National', u'Fantasysports', u'Sportfm',
                 u'Warnie', u'Dream', u'Dttalk', u'Team', u'Chris Digiovanni', u'Chris Nocal', u'Fantasy Advice',
                 u'Prospects', u'Tony Cincotta', u'Fantasy Basketball Podcast', u'Motorsport', u'Motorsports',
                 u'Formula', u'Grand', u'One', u'Prix', u'Ferrari', u'Auto', u'Vettel', u'Formula 1', u'Formulaone',
                 u'Formula1', u'Motor Racing', u'Nhl', u'England', u'Mls', u'Hockey', u'Premier League',
                 u'Fantasy Soccer', u'Melnick', u'Rotoballer', u'Here', u'Alec', u'Fascinating People', u'Thing',
                 u'Baldwin', u'Dad', u'Twins', u'Motherhood', u'Dads', u'Parenthood', u'Timmcgraw',
                 u'Female Pop Singers', u'Taylorswift', u'Spears', u'Ateam', u'Fearless', u'1989', u'Red',
                 u'Tmoneybagels', u'Electropop', u'Britney', u'Technopop', u'Wilhite', u'Swift', u'Newwave',
                 u'Chillwave', u'Singer Songwriter', u'Fantasy Hockey', u'Ice', u'Fantasyhockey', u'Playoffs',
                 u'Banter', u'Producer', u'FilMMAker', u'Videography', u'Screenplay', u'Screenwriter',
                 u'Cinematography', u'Final', u'Mmo', u'Final Fantasy', u'Final Fantasy Xi', u'Ffxiv',
                 u'Final Fantasy Xiv', u'Finalfantasy', u'Mmorpg', u'Ffxi', u'Limit Break Radio', u'Personal Finances',
                 u'Personalfinance', u'Debt', u'Retirement', u'Commodities', u'Estate', u'Forex', u'Fine', u'Beauty',
                 u'Fashion and Beauty', u'Fashion', u'Shade', u'Celebrity', u'Browncoat', u'Serenity', u'Sci', u'Fi',
                 u'Fishing', u'Fly', u'Flyfishing', u'Archery', u'Orvis', u'Rut', u'Hunting', u'Largemouth', u'Trout',
                 u'Deer', u'Doe', u'Saltwaterfishing', u'Bassfishing', u'Fitness Industry', u'Bodybuilding', u'Loss',
                 u'Fatloss', u'Personaldevelopment', u'Paleo', u'Mindset', u'Workouts', u'Fitness Business', u'Lifting',
                 u'Techmtb', u'Mountainbiking', u'Special', u'Johnn', u'Birthdays', u'Rider', u'Cash', u'Beginner',
                 u'Events', u'Today', u'Famous', u'Skills', u'Guests', u'Products', u'Trails', u'Poems', u'Daubat',
                 u'Bluegrass', u'Festival', u'Singersongwriter', u'Newport', u'Acoustic', u'Demarzi', u'Folkmusic',
                 u'Country', u'Foodpodcast', u'Eating', u'Kitchen', u'Beer', u'Fellowship Church', u'Remix', u'Wine',
                 u'Tacoma', u'Recipes', u'Gage', u'Fellowship Knoxville', u'Schaeffer', u'House Fellowship', u'Lfc',
                 u'Steven Gerrard', u'Football Manager', u'Manager', u'Anfield', u'Fanduel', u'Interactive',
                 u'Dailyfantasysports', u'Clients', u'Freelancer', u'Copywriting', u'Hustle', u'Marzulli', u'Voice',
                 u'Oberservers', u'Conspiratorial', u'Tvshow', u'Network', u'L', u'Future', u'Touchpad', u'Gunrights',
                 u'2ndamendment', u'Honeycomb', u'Playbook', u'Rim', u'Pre', u'Windows', u'Hardware', u'2a',
                 u'Blackberry', u'Webos', u'Poker', u'Slots', u'Table Top Games', u'Casino', u'Blackjack', u'Machines',
                 u'Netrunner', u'Slot', u'Craps', u'Vegas', u'Lcg', u'Betting', u'Game Development', u'Game Dev',
                 u'Gamedesign', u'Dev', u'Gamedevelopment', u'Gamedev', u'Developers', u'Fire', u'Gameofthrones',
                 u'Song', u'Asoiaf', u'George', u'Lannister', u'Got', u'Martin', u'Georgerrmartin', u'Dice',
                 u'Roleplayinggame', u'Boardgames', u'Plant', u'Horticulture', u'Plants', u'Sufficient', u'Vegetable',
                 u'Vegetablegardening', u'Organicvegetables', u'Women', u'Intersectional', u'Feminism', u'Gender',
                 u'Rabble', u'Family History', u'Ancestry', u'Archives', u'Social Media', u'Geneology',
                 u'Genealogy Society', u'Tree', u'Genealogytips', u'Freegenealogy', u'Genetic', u'Genomics',
                 u'Phenotype', u'Biotech', u'Genotype', u'Dna', u'Therapies', u'Genes', u'Garmin', u'Mngca',
                 u'Geocache', u'Caching', u'Gps', u'Treasure', u'Hobby', u'Minnesota', u'Geo', u'Activity', u'Gpsr',
                 u'Heads', u'Geospatial', u'Cartography', u'Gis', u'Military', u'Maps', u'Biography', u'K 12',
                 u'Century', u'Medieval', u'Normans', u'Europe', u'Sciences', u'Anthropocene', u'Generation',
                 u'Stanford', u'Mill', u'Flood', u'Lorelai', u'Rory', u'Spring', u'Gilmore Girls', u'River',
                 u'Gilmoregirls', u'Hollow', u'Luke', u'Choir', u'Project', u'Marc Maron', u'Musicals', u'Musical',
                 u'Recapshow', u'Kevin Smith', u'Elm', u'Haskell', u'Erlang', u'Scala', u'Clojure',
                 u'Functional Programming', u'Clojurescript', u'Pgatourradio', u'Nolayingup', u'Pga', u'Courses',
                 u'Pgatour', u'Rap', u'Gospel Music', u'Inspirational', u'R&b', u'Urban', u'Serena', u'Blair',
                 u'Meester', u'Gossip', u'Gossip Girl', u'Chuck', u'Lively', u'New Media Factory', u'Waldorf', u'York',
                 u'Wayne', u'Leighton', u'Bruce', u'Bruce Wayne', u'Gordon', u'User Experience', u'Experience', u'Blog',
                 u'Interiordesign', u'Web Development', u'Jla', u'Woman', u'Green Lantern', u'Wonder', u'Lantern',
                 u'Justice', u'Transition', u'Eco', u'Renewable Energy', u'Scandal', u'Cleanse', u'Candita', u'Callie',
                 u'T', u'Itunes Podcaster', u'Greysanatomy', u'Bloating', u'Estrogen', u'Alkaline',
                 u'Alternativemedicine', u'Rabbit', u'Alternativehealth', u'Purposeful', u'Outlaws', u'Cowboy',
                 u'Fights', u'Gun', u'Old Time Radio', u'Dillon', u'Alohomora', u'Mugglecast', u'Harry Potter',
                 u'Jkrowling', u'Potter', u'Harrypotter', u'Rowling', u'Harry', u'Sorcerer', u'Mugglenet',
                 u'Health Care', u'Stone', u'Health Industry', u'Telehealth', u'Ehr', u'Mhealth', u'Emr', u'Glidden',
                 u'Care', u'Gliddenhealthcare', u'Report', u'Permaculture', u'Callstohealth', u'Samadi', u'Sexuality',
                 u'Healthcoaching', u'Sambearfoot', u'Digestivewellness', u'Digestiondetective', u'Seaward',
                 u'Warcraft', u'Card', u'Wow', u'Decks', u'Blizzard', u'Tcg', u'Ccg', u'Hearth',
                 u'Eatinghealthyeatingnutritionoverweighteatingdisordersholisticdietitian', u'Yoga',
                 u'Lossbulimiabinge', u'Solidjake', u'Blizzheroes', u'Heroesofthestorm', u'Storm',
                 u'Heroes of the Storm', u'Zoia', u'Hots', u'Townhall', u'Town', u'Hall', u'Starcraft', u'Fender',
                 u'Peter Hodgson', u'Gibson', u'Amplifier', u'Blues', u'10 Years', u'Classical', u'Hinduism', u'Iskcon',
                 u'Radha', u'Krishna', u'Epic', u'Mahabharata', u'India', u'Kirtan', u'Islam', u'Nyc', u'Hip Hop',
                 u'Mixtape', u'Listen', u'Hip Hop & Rap', u'Pataliputra', u'Mauryan', u'Ancient', u'Nerds', u'Jainism',
                 u'Gupta', u'Ganges', u'Worldhistory', u'Motorcycle', u'Noobtoob', u'Ukelele', u'Sailing',
                 u'Karnivalkarnage', u'Woodworking', u'Hotpepper', u'Fonetica', u'Bilingual Homeschool',
                 u'Homeschoolmoms', u'Homeschool Transcripts', u'Hsdla', u'Homeschool Laws', u'Hsld', u'Leah Ramirez',
                 u'Hslda', u'Homeschool Heartbeat', u'Home School', u'Highereducation', u'Higher', u'Colleges',
                 u'University', u'Scary', u'Horror Stories', u'Urdu', u'Handicapping', u'Horse Racing',
                 u'Betting On Horses', u'Picks', u'Horse Breading Information', u'How To Win A Horse Race',
                 u'Horse Competition', u"World's Leading Auctions", u'How To Buy A Horse', u'Learning About Auctions',
                 u'Sales Ring Insider', u'Cup', u'Horse Races', u'Riding the Storm Out', u'Maureen Ennor',
                 u'Bear Stearns', u'the Hockey Writers', u'HouSEOfcards', u'Echl', u'Cards', u'Binge',
                 u'Edmontonoilers', u'Ahl', u'Canadiens', u'Canucks', u'Flames', u'Stanley Cup', u'Peopleanalytics',
                 u'Hr', u'Humanresources', u'Employees', u'Hiring', u'Employee', u'Employee Engagement',
                 u'International', u'Human Rights', u'Ethics', u'Canada', u'Civil', u'Irp6', u'Terror', u'Movie',
                 u'Blood', u'Creepy', u'Gore', u'Supernatural', u'Halloween', u'Linguistics', u'Linguistics Education',
                 u'Mockingjay', u'Ethical Living', u'Satire', u'Hunger', u'Hunger Games', u'Catching Fire', u'Catching',
                 u'Collins', u'Suzanne', u'Bowhunting', u'Whitetail', u'Buck', u'Crappie', u'Catfish', u'Hunter',
                 u'Blue', u'Hypnotherapy', u'Anxiety', u'Hypnotist', u'Nlp', u'Newland', u'Relaxation', u'Hypnotism',
                 u'Jason', u'Stress', u'Confidence', u'Whr', u'Drupal', u'Freelancing', u'Roundup', u'Pmp', u'Itil',
                 u'Pmi', u'Cobit', u'Genetics', u'Cell', u'Cio', u'Itsmf', u'Rheumatology', u'Multiple Sclerosis',
                 u'Developmental Biology', u'Vocational Status', u'Health Related', u'Molecular Biology',
                 u'Systems Biology', u'Happiness', u'Improvement', u'Hypnosis', u'Esteem', u'Inclusion',
                 u'Disabilities', u'Inclusive', u'Uni Erlangen', u'LGBT', u'Welcoming', u'Fau', u'Eeo', u'Indie Music',
                 u'Indiemusic', u'Concerts', u'Bands', u'Kevin Pike', u'Ip', u'Intellectual Property', u'Ebm',
                 u'Copyright', u'Trademark', u'Intellectual', u'Intellectualproperty', u'Property', u'Legal', u'Patent',
                 u'Interior Design', u'Interior', u'Decor', u'Hgtv', u'Deanna Radaj', u'Interiors', u'Furniture',
                 u'Designer', u'Bante Design', u'Homeland Security', u'Danes', u'Sbs', u'Claire', u'Mathison',
                 u'Damian', u'Terrorism', u'Nicholas', u'International Relations', u'Foreign', u'Relations',
                 u'Government', u'Policy', u'Thinktank', u'Internationalrelations', u'Cfr', u'Diplomacy',
                 u'Councilonforeignrelations', u'Cpop', u'Kpop', u'Kei', u'Jpop', u'Jrock', u'Japanese', u'J',
                 u'Korean', u'Asian', u'Korea', u'K Pop', u'Bond', u'James', u'Visual', u'James Bond', u'Spy',
                 u'Connery', u'007', u'Brosnan', u'Moore', u'Sean', u'Css', u'Objective', u'Languages', u'Html',
                 u'Throwdown', u'Funk', u'Smooth', u'Bebop', u'Fusion', u'Straight', u'Piano', u'Ahead', u'Judaism',
                 u'Israel', u'Echad', u'Eloheinu', u'Chadasha', u'Deceived', u'Torah', u'Delivered', u'Alephbet',
                 u'Audiompeg', u'Pulmonary', u'American Journal of Psychiatry', u'Schizophrenia', u'Rehab',
                 u'Depression', u'Eating Disorders', u'American Psychiatric Association', u'Psychiatry', u'Muslim',
                 u'Muslims', u'Quran', u'MuhaMMAd', u'Shia', u'Muhammed', u'Koran', u'Allah', u'Sunni', u'Moslem',
                 u'Prophet', u'About', u'Fiqh', u'Seerah', u'Yarn', u'Fiber', u'Fibre', u'Ravelry', u'Spinning',
                 u'Knits', u'Heartlandknits', u'Spin', u'Weaving', u'Transgender', u'Gay', u'Bisexual', u'Popculture',
                 u'Glbt', u'Lgbtq', u'Ingles', u'Anglais', u'Englis', u'Eslpod', u'Els', u'Languagelearning', u'Pod',
                 u'Learning Spanish', u'Polish', u'Www.raystedman.org', u'Last Resort', u'Ray Steadmen',
                 u'New Testament', u'Exposition', u'Timothy', u'Commentary', u'Holy Spirit', u'Latin', u'Salsa',
                 u'Latin Music', u'Afro', u'40', u'Reggaeton', u'Beats', u'Lawyers', u'Gas', u'Oil', u'Colloquial',
                 u'Texas', u'Modern', u'Litigation', u'Flagship', u'Glossaries', u'Houston', u'Glossary', u'Exo', u'K',
                 u'Kdrama', u'Jini', u'Bts', u'Bigbang', u'Korean Entertainment', u'Trainee', u'Got7', u'Jyp',
                 u'Leagueoflegends', u'Elo', u'Iem', u'Lcs', u'Riot', u'League of Legends', u'Dota', u'F2p',
                 u'Arabicpod101', u'Learning Arabic', u'Arabic', u'Chinesepod', u'Islamic', u'Chinese',
                 u'Learning Chinese', u'Mandarin', u'Chinese Pod', u'Hsk', u'Beijing', u'Hong Kong', u'Learn Chinese',
                 u'Cantonese', u'Shanghai', u'Chinese Podcast', u'Learn Mandarin', u'Course', u'Frenchpod.com',
                 u'Frenchpod', u'Frenchpod101', u'French', u'Learning French', u'Nacogdoches', u'Learn French',
                 u'German', u'Francais', u'Learning German', u'Deutsch', u'Germanpod101', u'Podcasts', u'Intermediate',
                 u'Italian', u'Italy', u'Germany', u'Romantic', u'Learning Italian', u'Italiano', u'Phrases', u'Visit',
                 u'Leader', u'Strategy', u'Mind', u'Leaders', u'Survivalphrases.com', u'Learning Korean',
                 u'Survival Phrases', u'Portuguese', u'Lesson', u'Brazilian', u'Portugues', u'Aulas', u'Brazil',
                 u'Brazileiro', u'Learning Portuguese', u'Brazilianpodcast', u'Portugal', u'Learning Russian',
                 u'Classes', u'Sang', u'Brasil', u'Russianpod101', u'Russia', u'Spanishpod.com', u'Beginners',
                 u'Spanish', u'Ecuador', u'Argentine', u'Real', u'Colombian', u'Agorism', u'Agorist', u'Libertarianism',
                 u'Liberty', u'Freedom', u'Paxlibertasproductions', u'Anarchist', u'Voluntaryist', u'Libertarianparty',
                 u'Indiana', u'Indianapolis', u'Budgettravel', u'Travelpodcast', u'Productivity', u'Thelinguist',
                 u'Words', u'Lingq', u'Etymology', u'Japanesepod101.com', u'Japanesepod101', u'Nihongo', u'Tesol',
                 u'Linguist', u'Tefl', u'Language Courses', u'Applied', u'Jlpt', u'Learning Japanese', u'Osaka',
                 u'Software Freedom', u'Open', u'Tech Interviews', u'Unix', u'Community Radio', u'Tokyo',
                 u'Linux Education', u'Drinks', u'Cocktails', u'Bartending', u'Booze', u'Alcohol', u'Spirits',
                 u'Mixology', u'Whisky', u'Bar', u'Cocktail', u'Bartender', u'Liverpool Football Club', u'Liverpoolfc',
                 u'Fc', u'Koppage', u'Lfctv', u'Jamie Carragher', u'Sport', u'Kenny Dalglish', u'Ian Ayre',
                 u'J.R.R. Tolkien', u'Rings', u'Tolkien', u'Lord', u'Hobbit', u'Lord of the Rings', u'Lotr', u'Jrr',
                 u'Lotro', u'Fan', u'Discussion', u'Kfuo', u'Lcms', u'Elca', u'Luther', u'Wisconsin',
                 u'Creating Good Ads', u'Masters', u'Gmat', u'Advertising Strategy', u'Wharton', u'Marketing Message',
                 u'EMBA', u'Digital Education Twou', u'Paucek', u'Graduate', u'Business School', u'Gnome', u'Libre',
                 u'Degree', u'Kde', u'Gtk', u'Foss', u'Qt', u'Arch', u'Chrome', u'Opensource', u'Unity', u'MS Dev',
                 u'Powershell', u'Microsoft', u'r', u'Mapping', u'Windows8', u'Vb', u'Mapper', u'Practices', u'Atlas',
                 u'Scripting', u'Mad Men', u'Men', u'Toner', u'Mad', u'Madmen', u'Low', u'Magic the Gathering', u'Mtg',
                 u'Gathering', u'Magic: the Gathering', u'Game Design', u'Blake Rasmussen', u'Dailymtg', u'Magic Story',
                 u'Mark Rosewater', u'Duels of the Planeswalkers', u'Manchester City Football Club', u'Summerbee',
                 u'Pickering', u'Rothband', u'Manchester City', u'Nigel', u'Roberto', u'Ultramarathon', u'Runwalkrun',
                 u'Ralston', u'Oroville', u'Ultra', u'Maniacs', u'Yen', u'Band', u'Franc', u'Bank', u'Dollar', u'Swiss',
                 u'Jse', u'Standard', u'Doyle', u'South', u'Aidan', u'Elliott', u'Martial', u'Fighting', u'Strikeforce',
                 u'Mixed Martial Arts', u'Bellator', u'Mixed', u'Ultimate', u'Championship', u'Cagefighting',
                 u'Wrestling', u'Bjj', u'Martial Arts', u'Taekwondo', u'Kung', u'Karate', u'Fu', u'Kungfu', u'Toys',
                 u'Hulk', u'Avengers', u'Shield', u'Marvel Comics', u'Iron', u'Maths', u'Geometry', u'Algebra',
                 u'Math Education', u'Sridhar', u'Level', u'Mathematical', u'Stem', u'Tamil', u'Mega64', u'Bert',
                 u'Center', u'Studies', u'Sports Medicine', u'Prepper Medicine', u'Disaster Survival', u'First Aid',
                 u'Sceptic', u'Pitman', u'Melbourne', u'Scepticism', u'Tony', u'Thinking', u'Critical', u'Husband',
                 u'Intimacy', u'Marriageadvice', u'Dating', u'Cheating', u"Men's Corner", u'Manliness',
                 u'Jordan Harbinger', u'Art of Charm', u"Men's Health", u'Purity', u'Masculinity', u'Mental',
                 u'Dating Advice For Men', u'Mentalillness', u'Mentalhealth', u'Empowerment', u'Counseling', u'Death',
                 u'Heavy', u'Death Metal', u'Thrash', u'Hard', u'Extreme', u'Black Metal', u'Shock', u'Heavymetal',
                 u'Finnish', u'Metaphysical', u'Astrology', u'Reiki', u'New Age', u'Ascension', u'Spirit',
                 u"J.g. M'pherson", u'Meteorology; Or Weather Explained', u'Ams', u'James Spann', u'Insight', u'Guided',
                 u'Metta', u'Vipassana', u'DhaMMA', u'Seed', u'Retreat', u'Michael Jackson', u'Radiant',
                 u'the Jackson 5', u'Jackson', u'Popenhagen', u'Michigan Wolverines', u'Harbaugh', u'Michigan',
                 u'Wolverines', u'Jim', u'Maize', u'Jim Harbaugh', u'Belein', u'Ncaa', u'Military History',
                 u'US Military', u'Veterans', u'US Veterans', u'Navy', u'Army', u'Marines', u'Airforce', u'Warfare',
                 u'Force', u'World War I', u'Wwii', u'Pc', u"Let's Play", u'Fun', u'Omgchad', u'Notch', u'Mojang',
                 u'Cnbc', u'Blended', u'Modern Family', u'Stocks', u'Budget', u'Wnyc', u'Stepsforbusinesscom',
                 u'Bookofmormon', u'Exmormon', u'Transitions', u'Lds', u'Mormons', u'Mormonism', u'Conference',
                 u'Doubt', u'United', u'United Methodist', u'Aldersgate', u'Aldersgate Umc', u'Umc', u'Reconciling',
                 u'Abilene', u'Georgia', u'Austin', u'Touring', u'Davidson', u'Harley', u'Motorcycles', u'Racer',
                 u'Motorbike', u'Cafe', u'Bikes', u'NASCAR', u'Offroad', u'Adam Morgan Btcc', u'Mac Tools',
                 u'Ciceley Racing', u'Adam Morgan', u'Motors', u'Cicely Motorsport', u'Corr', u'Ukf', u'Chillout',
                 u'Mixes', u'Songwriters', u'Electrkprincess', u'Musicindustry', u'Musician', u'Chh', u'Promotion',
                 u'Mother', u'Mom', u'Birth', u'Pregnancy', u'Moms', u'legends', u'Gods', u'Myth',
                 u'Dale Earnhardt Jr.', u'Earnhardt', u'Xfinity Series', u'Dale Jr.', u'Camping World Truck Series',
                 u'Sprint Cup', u'Sprint', u'Jr Nation', u'Number 88', u'Nba Basketball', u'Hoops', u'Bball', u'Hang',
                 u'Hangtime', u'Nbapodcast', u'Ringer', u'Toddeastman', u'Cleveland Cavaliers', u'Bill', u'Shounen',
                 u'Piece', u'Bleach', u'Gundam', u'Shonen', u'Jump', u'Native', u'Indigenous', u'Aboriginal',
                 u'Native American Talk Radio', u'Nativeamerican', u'Nativetalk.net', u'Tribal', u'American Indian',
                 u'Native American', u'Ryan', u'Mcmahon', u'Listener Mail', u'Puyallup Podcast', u'Dinosaurs', u'Stuff',
                 u'Ffg', u'Android:', u'Board', u'Channel', u'Agenda', u'Neoreading', u'Grid', u'Mysteries', u'Kine',
                 u'Chilling', u'Strange', u'Gimlet', u'Starlee', u'Brain', u'Neurology', u'Age', u'Metaphysics',
                 u'Chill', u'Newage', u'Space Music', u'Giants', u'Jersey', u'Mets', u'New York', u'Jets', u'Rangers',
                 u'New York Giants', u'Knicks', u'Islanders', u'Talkin', u'Laravel', u'Aferlife', u'Evp', u'Apparition',
                 u'Poltergeist', u'Investigation', u'Exorcism', u'Demons', u'News and Entertainment',
                 u'Political Comedy', u'Seth Meyers', u'Kissel', u'Review', u'Ben', u'News Talk', u'Chris Donoghue',
                 u'Arca Racing Series', u'K&n Pro Series', u'Fan4racing Radio', u'Irish Current Affairs', u'Ivan Yates',
                 u'Ithaca', u'Dual', u'Allen', u'David', u'3ds', u'Wii', u'Ds', u'Mario', u'Switch', u'Zelda',
                 u'Metroid', u'Splatoon', u'Gamecube', u'Wii U', u'Nx', u'N64', u'Sedation', u'Journal', u'Parkinson',
                 u'Sage', u'Ophthalmology', u'Stroke', u'Physical', u'Publications', u'Primal', u'Longevity',
                 u'Glutenfree', u'Fat', u'Marine Biology', u'Ocean', u'Sea', u'Marine Science',
                 u'Research Medical Healthcare Life', u'Shark', u'Marine', u'Pollution', u'Neill', u'Acidification',
                 u'Otter', u'Oklahoma City Thunder', u'Russell Westbrook', u'Oklahoma', u'Kevin Durant', u'Observatory',
                 u'Okc', u'Okcthunderheads', u'Thunderbasketball', u'Thunder', u'Oklahomacitybasketball',
                 u'Okc Thunder', u'Thunderheads', u'Westbrook', u'Sooners', u'Roll', u'Los Angeles', u'60s', u'Doo',
                 u'Rockabilly', u'Roots', u'Teenage', u'Once Upon A Time', u'Dancehall', u'Ouat', u'Upon',
                 u'Fairy Tales', u'Once', u'Grimm', u'Hematology', u'Peerview', u'Oncology and Hematology',
                 u'Radiation', u'Chemotherapy', u'Cancer Care', u'Nsclc', u'Gracecast', u'Cancergrace', u'Chemo',
                 u'Oss', u'Opensourcesex', u'Violetblue', u'Changelog', u'Pti', u'Violet', u'Simmons', u'Nonprofits',
                 u'Nonprofit', u'Fundraising', u'Profit', u'Ngo', u'Non Profit', u'Not For Profit', u'Charity',
                 u'Philanthropy', u'Retina', u'Cataract', u'Glaucoma', u'Cornea', u'ce', u'Eyes', u'Duke Health',
                 u'Diabetes and Endocrinology', u'Optometry', u'Spine', u'Plsql', u'Solaris', u'Htmldb', u'Jquery',
                 u'Sql', u'Database', u'Apex', u'Sun', u'Applications', u'Giantbomb', u'Giant Bomb', u'Sony', u'Wiiu',
                 u'Ps3', u'Xbox 360', u'Wicca', u'Magick', u'Witchcraft', u'Witch', u'His', u'Wiccan', u'Alchemy',
                 u'Heathen', u'Pagans', u'Two', u'Hermeticism', u'Tylergreen', u'Visualart', u'Jayhawks', u'Painted',
                 u'Ku', u'Door', u'Kansas', u'This Week In Paleo', u'Intermittent Fasting', u'Paleo Fitness',
                 u'Barefoot', u'Paleo Diet', u'Solution', u'Wolf', u'Robb', u'Intermittent', u'Fasting', u'Forensics',
                 u'Parents', u'Boettcher', u'Apostolic', u'Bartlett', u'Yonts', u'11 Commission Report',
                 u'11 Commission', u'Transwoman', u'Maggie Smith', u'Mr Selfridge', u'Peaky Blinders', u'Garden',
                 u'Ecology', u'Forest', u'Gardens', u'Planning', u'Frugality', u'Exotic Pets', u'Pet Health', u'Fish',
                 u'Clinical Pharmacology', u'Ascpt', u'Cardiology', u'Peervoice', u'Medication',
                 u'Continuing Medical Education', u'Aristotle', u'Alwan', u'Paskin', u'Bigfoot', u'UFOs', u'Ufos',
                 u'Hauntings', u'Physical Therapy', u'Physicaltherapy', u'Therapy', u'Physiotherapy', u'Rehabilitation',
                 u'Pt', u'Pain', u'Injury', u'Geriatrics', u'Mechanics', u'Albeniz', u'Materials', u'Contemporary',
                 u'Improvisation', u'Npr', u'Movement', u'Workout', u'Scientificresearch', u'Humanmovementscience',
                 u'Bally', u'Stern', u'Williams', u'Gottlieb', u'Hunters', u'Lucasfilm', u'Dreamworks', u'Character',
                 u'Starwars', u'Animator', u'Vita', u'PlayStation', u'Psp', u'Official', u'Ign', u'Scotland',
                 u'Scottish', u'Ps2', u'Ps', u'Blumberg', u'Camera', u'Photo', u'Photoshop', u'Mirrorless',
                 u'Photographer', u'Cameras', u'Dslr', u'Apes', u'Viola', u'Poetry Reading', u'Howes', u'Cello',
                 u'String', u'Poets', u'Poem', u'Readings', u'Library', u'Literary', u'Spoken Word', u'Author Readings',
                 u'Opinion & Commentary', u'Writers', u'Go', u'Pok\xe9mon', u'Pkmn', u'Pokemongo', u'Gameboy',
                 u'Holdem', u'Pokertraining', u'Startingpoker', u'Pokercast', u'Pokervideo', u'Smartpokerstudy',
                 u'Skymatsuhashi', u'Pokerstrategyliteraturesubject', u'Pokerstrategy', u'Tyt', u'Theyoungturks',
                 u'Crowder', u'Cenkuygur', u'Pokertips', u'President', u'Electoral College', u'Electors',
                 u'President Elect', u'Vote', u'White House', u'Politicalscience', u'Atheism', u'Elections',
                 u'Onyourownadventures', u'UK Politics', u'Newberg', u'Sanders', u'Election 2016', u'Mule', u'Lands',
                 u'Hunttalk', u'Starchman', u'Thenewsworthy', u'Newsworthy', u'SuMMAry', u'Highschool',
                 u'Diane Rehm Show News Roundup Wamu Npr National Public Radio Politics News', u'Turkey', u'Usda',
                 u'Chickens', u'Truffle', u'Influenza', u'Dairy', u'Avian', u'Chicken', u'Cow', u'Sentai', u'Mighty',
                 u'Powerrangers', u'Power Rangers', u'Super', u'Morphin', u'Dino', u'Kamen', u'Gokaiger', u'Tokusatsu',
                 u'Transformers', u'Dornblaser', u'Pca', u'Davis', u'Cherrybrook', u'Lauren', u'Weaver', u'Dorothy',
                 u'Dudley', u'Mcdonald', u'Liars', u'Pretty', u'Little', u'Pll', u'Dilaurentis', u'Pretty Little Liars',
                 u'Alison', u'Tna', u'Wrestlemania', u'Smackdown', u'Roman Reigns', u'Prowrestling', u'Raw',
                 u'John Cena', u'Sports Entertainment', u'Task Management', u'Productmanagement', u'Gtd', u'Goals',
                 u'Time Management', u'Cplusplus', u'Ernani Joppert', u'Manuel Lemos', u'Phpclasses', u'Prog Languages',
                 u'Node.js', u'Cpp', u'Node', u'Functional', u'Code', u'Program', u'Progressive House', u'Trance',
                 u'Vocal Trance', u'Progressive Trance', u'Melodic House', u'Electro House', u'Deep House', u'Pdu',
                 u'Fichtner', u'Projectmanagement', u'Cornelius', u'Pm', u'Projects', u'Project Management',
                 u'Pmpodcast', u'Reformation', u'Refromed', u'Curriculum', u'Sinners', u'Urc', u'Calvinism',
                 u'Dsm Iv Tr. Dsm 5', u'Adhd', u'Psychic Readings', u'Tarot', u'Intuition', u'Psychic Medium',
                 u'Medium', u'Free Psychic Readings', u'Clairvoyant', u'Angels', u'Sigmund Freud', u'Dream Psychology']

topics = ['Accounting', 'Accounting Education', 'Acoustic', 'Activism', 'Activism Roundup', 'Adventist',
          'African American', 'After Life', 'Agile', 'Agriculture', 'Agriculture Roundup', 'Alcatraz', 'Alternative',
          'Alternative Health', 'Alternative Health Roundup', 'Alternative Spirituality', "Alzheimer's Disease",
          'American Football', 'American Football Roundup', 'American Horror Story', 'American Idol', 'Anatomy',
          'Anatomy Education', 'Android', 'Angels', 'Anglican', 'Animal Rights', 'Animals and Pets', 'Animated Fiction',
          'Animation', 'Anime', 'Anthropology', 'Anthropology Education', 'Apostolic', 'App Business',
          'App Business Education', 'Apple', 'Arcade Games', 'Archaeology', 'Archaeology Education', 'Architecture',
          'Architecture Education', 'Arkansas Razorbacks', 'Arrow', 'Arsenal Football Club', 'Artificial Intelligence',
          'Arts', 'Arts Roundup', 'Astrology', 'Astronomy', 'Astronomy Education', 'Atheism', 'Audio Theater',
          'Audiobooks', 'Aussie Rules', 'Authors', 'Autism', 'Auto', 'Avatar - The Last Airbender', 'Aviation', 'Bands',
          'Baptist', 'Baseball', 'Baseball Roundup', 'Basketball', 'Basketball Roundup', 'Batman',
          'Battlestar Galactica', 'Bedtime Stories', 'Beekeeping', 'Beer', 'Being Human', 'Better Call Saul',
          'Bible Prophecy', 'Big Brother', 'Bigfoot', 'Biology', 'Biology Education', 'Biotech', 'Birds', 'Blogging',
          'Blues', 'Bodybuilding', 'Bollywood', 'Books', 'Books and Writing', 'Boxing', 'Breaking Bad', 'Breaking News',
          'Brethren', 'Buddhist', 'Buffy the Vampire Slayer', 'Business', 'Business Disciplines', 'Business Education',
          'Business English', 'Business News', 'Business Trends', 'Cardiology', 'Careers', 'Castle', 'Catechesis',
          'Catholic', 'Cats', 'Chemistry', 'Chemistry Education', 'Chess', 'Chicago Cubs', 'Chiropractic', 'Christian',
          'Christian Apologetics', 'Christian Orthodox', 'Christian Students', 'Christianity', 'Cinema',
          'Cinema Roundup', 'Classic Radio', 'Classic Sitcoms', 'Classic TV', 'Classic TV Roundup', 'Classical',
          'Clean Comedy', 'Climate Change', 'Climbing', 'Cloud IT', 'Cloud IT Education', 'Coaching', 'Combat Sports',
          'Comedian Chat', 'Comedian Interviews', 'Comedy', 'Comics', 'Comics Roundup', 'Communities',
          'Community Church', 'Computer Science', 'Conservative', 'Conspiracy Theories', 'Conversations',
          'Cosmetic Surgery', 'Country', 'Creativity', 'Cricket', 'Crime', 'Cruising', 'Current Affairs', 'Current TV',
          'Cyber Currency', 'Cycling', 'DC', 'Daily Business News', 'Daily News', 'Daily Tech News', 'Dark Souls',
          'Darts', 'Data Science', 'Dating', 'Dentistry', 'Desperate Housewives', 'Destiny', 'DevOps', 'Dexter',
          'Diabetes', 'Digital Marketing', 'Disc Golf', 'Disney', 'Do It Yourself', 'Doctor Who', 'Documentaries',
          'Dogs', 'Dollhouse', 'DotA', 'Downton Abbey', 'Dragnet', 'Drama', 'Drones', 'Drum and Bass', 'Drupal',
          'Dungeons and Dragons', 'E-Commerce', 'E-Commerce Education', 'Eclectic', 'Economics', 'Education',
          'Education Tech', 'Electronic', 'Elite: Dangerous', 'Elvis Presley', 'Emergency Medicine', 'Endurance Sports',
          'Energy', 'Engineering', 'English Pronunciation', 'English Usage', 'Entertainment', 'Entertainment Industry',
          'Entrepreneur', 'Entrepreneur Interviews', 'Entrepreneur Lifestyle', 'Entrepreneur Roundup', 'Environment',
          'Environment Roundup', 'Equestrian', 'Evangelical', 'F1', 'Facts and Trivia', 'Falling Skies', 'Family',
          'Fantasy', 'Fantasy American Football', 'Fantasy Aussie Rules', 'Fantasy Baseball', 'Fantasy Basketball',
          'Fantasy Hockey', 'Fantasy Soccer', 'Fantasy Sports', 'Fantasy Sports Roundup', 'Fascinating People',
          'Fashion and Beauty', 'Fatherhood', 'Fellowship', 'Female Pop Singers', 'Feminist', 'Filmmaking',
          'Final Fantasy', 'Finance', 'Fine Arts', 'Firefly', 'Fish', 'Fishing', 'Fitness', 'Fitness Industry',
          'Fitness Roundup', 'Folk', 'Food', 'Food and Beverage', 'Football Manager', 'Freelancing', 'Fringe',
          'Future Trends', 'Gadgets', 'Gambling', 'Game Development', 'Game of Thrones', 'Games and Gambling',
          'Gardening', 'Geekery', 'Genealogy', 'Genetics', 'Geocaching', 'Geography', 'Geology', 'Geology Education',
          'Gilmore Girls', 'Glee', 'Go To Sleep', 'Golf', 'Gospel Music', 'Gossip Girl', 'Gotham', 'Graphic Design',
          'Green Lantern', 'Greentech', "Grey's Anatomy", 'Guitar', 'Gunsmoke', 'Harry Potter', 'Health Care',
          'Health Industry', 'Health News', 'Health and Well-Being', 'Hearthstone', 'Heroes of the Storm',
          'Higher Education', 'Hindu', 'Hiphop', 'History', 'Hobbies', 'Hockey', 'Hockey Roundup', 'Holistic Health',
          'Homeland', 'Homeschooling', 'Horror', 'Horror Roundup', 'Horror Stories', 'Horseracing', 'House of Cards',
          'Human Resources', 'Human Rights', 'Humanities Education', 'Humor', 'Hunger Games', 'Hunting', 'Hypnosis',
          'IT Industry', 'IT Management', 'Immunology', 'Improv', 'Inclusive Education', 'Indie Music', 'Industries',
          'Intellectual Property', 'Interior Design', 'International News', 'International Relations', 'Islamic',
          'J-pop', 'J.R.R. Tolkien', 'James Bond', 'Java', 'Jazz', 'Jewish', 'Journalism', 'Justified', 'K-pop',
          'Kids and Family', 'Knitting', 'LGBT', 'Language Learning', 'Last Resort', 'Latin Music', 'Law',
          'Law Roundup', 'Leadership', 'League of Legends', 'Learning Arabic', 'Learning Chinese', 'Learning English',
          'Learning English Roundup', 'Learning French', 'Learning German', 'Learning Hindi', 'Learning Italian',
          'Learning Japanese', 'Learning Korean', 'Learning Portuguese', 'Learning Russian', 'Learning Spanish',
          'Libertarian', 'Lifestyle', 'Linguistics', 'Linguistics Education', 'Linux', 'Linux Education', 'Liquor',
          'Liverpool Football Club', 'Lord of the Rings', 'Lost', 'Lutheran', 'MBA', 'MBA Education', 'MMA', 'MS Dev',
          'Mad Men', 'Magic: The Gathering', 'Manchester City Football Club', 'Marathon', 'Marketing',
          'Marketing Education', 'Marketing Roundup', 'Marriage', 'Martial Arts', 'Marvel', 'Math', 'Math Education',
          'Mature Comedy', 'Media', 'Medicine', 'Medicine Roundup', 'Meditation', "Men's Corner",
          "Men's Corner Roundup", "Men's Health", 'Mental Health', 'Mental Health Roundup', 'Metal', 'Metaphysics',
          'Meteorology', 'Methodist', 'Michael Jackson', 'Michigan Wolverines', 'Military', 'Military History',
          'Minecraft', 'Modern Family', 'Money', 'Mormon', 'Motherhood', 'Motorcycle', 'Motorsports',
          'Motorsports Roundup', 'Music', 'Music Business', 'Music Industry', 'Musicality', 'Musicians', 'Mystery',
          'Mythology', 'NASCAR', 'NBA', 'NBA Roundup', 'Naruto', 'Native American', 'Natural Sciences', 'Netrunner',
          'Neurology', 'Neuroscience', 'New Age', 'New York Giants', 'News', 'News Comedy', 'News Talk',
          'News and Entertainment', 'Nintendo', 'Non-Profit', 'Nutrition', 'Nutrition Roundup', 'Oceanography',
          'Oklahoma City Thunder', 'Oldies', 'Once Upon a Time', 'Oncology', 'Open Source', 'Operating Systems',
          'Ophthalmology', 'Oracle', 'Outdoor', 'PC Gaming', 'Paganism', 'Painting', 'Paleo', 'Paleontology',
          'Paranormal', 'Parenting', 'Pentecostal', 'Period Drama', 'Permaculture', 'Personal Finances', 'Pets',
          'Pharmacology', 'Philosophy', 'Photography', 'Physical Therapy', 'Physics', 'Piano', 'Pilates', 'Pinball',
          'Pixar', 'PlayStation', 'Podcasting', 'Podcasting Education', 'Poetry', 'Poetry Reading', 'Pokemon', 'Poker',
          'Political Comedy', 'Political Drama', 'Political Science', 'Politics', 'Politics Roundup', 'Pop',
          'Pop Culture', 'Poultry', 'Power Rangers', 'Presbyterian', 'Pretty Little Liars', 'Pro Wrestling',
          'Productivity', 'Prog Languages', 'Programming', 'Programming Education', 'Progressive', 'Project Management',
          'Protestant', 'Psychiatry', 'Psychic', 'Psychology', 'Psychology Education', 'Public Relations', 'Publishing',
          'Publishing Education', 'Qigong And Tai Chi', 'Quilting', 'Real Estate', 'Real Estate Education',
          'Reality TV', 'Reality TV Roundup', 'Recent TV', 'Reggae', 'Reiki', 'Relationship', 'Relationship Roundup',
          'Religion', 'Religion Roundup', 'Retro', 'Retro Gaming', 'Revolution', 'Rock', 'Rocky', 'Romance', 'Ruby',
          'Rugby', 'RuneScape', 'Running', 'SEO', 'SEO Education', 'Sailing', 'Sailormoon', 'Sales', 'Salvation Army',
          'Scandal', 'School Education', 'Sci-Fi', 'Sci-Fi / Fantasy Stories', 'Sci-Fi Roundup', 'Science',
          'Science Education', 'Science Roundup', 'Screenwriting', 'Secret Circle', 'Security', 'Self-Help',
          'Self-Improvement', 'Serial', 'Sexuality', 'Shakespeare', 'Shamanism', 'Sherlock Holmes', 'Short Stories',
          'Showbiz', 'Skeptic', 'Sketch Comedy', 'Sleepy Hollow', 'Smallville', 'Soap Opera', 'Soccer',
          'Soccer Roundup', 'Social Media', 'Social Media Education', 'Social Sciences', 'Society', 'Sociology',
          'Sociology Education', 'Software Development', 'Soul', 'Soundtrack', 'South America', 'South Park',
          'Spartacus', 'Specialized News', 'Spiritual Beings', 'Sports', 'Sports Betting', 'Sports Medicine',
          'Sports News', 'Sports and Entertainment', 'Spy', 'Stand-up Comedy', 'Star Trek', 'Star Wars', 'Stargate',
          'Storytelling', 'Strength Training', 'Superheroes', 'Superman', 'Supernatural', 'Survivor', 'Swimming',
          'Sysadmin', 'TV', 'TV Roundup', 'Table Top Games', 'Table Top Games Roundup', 'Tarot', 'Taxation', 'Teaching',
          'Teaching Trends', 'Tech', 'Tech Education', 'Tech News', 'Tech Startups', 'Tech Tips', 'Tennis',
          'Terra Nova', 'The Americans', 'The Bachelor', 'The Beatles', 'The Blacklist', 'The Elder Scrolls',
          'The Flash', 'The Following', 'The Newsroom', 'The Real Housewives', 'The Simpsons', 'The Strain',
          'The Twilight Zone', 'The West Wing', 'The Young and the Restless', 'Theater', 'Theme Parks', 'Theology',
          'Toronto Blue Jays', 'Toronto Maple Leafs', 'Tottenham Hotspur Football Club', 'Toys', 'Trading',
          'Transformers', 'Travel', 'Travel Roundup', 'Triathlon', 'True Blood', 'True Crime', 'True Crime Roundup',
          'True Detective', 'True Stories', 'Twilight', 'UFOs', 'UK Politics', 'US Government', 'US Military',
          'US Military Family', 'US Veterans', 'Ukulele', 'Unitarian Universalist', 'Urban Survival', 'User Experience',
          'Vampire Diaries', 'Varsity Teams', 'Vegan', 'Venture Capital', 'Video Game Music', 'Video Games',
          'Video Games Roundup', 'Walking Dead', 'Warhammer', 'Washington Redskins', 'Weather Alerts',
          'Web Development', 'Web Development Education', 'Weightlifting', 'Westworld', 'Whiskey', 'Windows', 'Wine',
          "Women's Corner", "Women's Corner Roundup", "Women's Health", 'Woodworking', 'Wordpress', 'World of Warcraft',
          'Worldbuilding', 'Writing', 'X Factor', 'X-Files', 'Xbox', 'Yoga']

podcasts_tags.sort()
with open('playfm_data.txt', 'w') as fh:
    fh.write('---------- topics ----------\n')
    fh.write('\n'.join(topics))
    fh.write('\n\n\n')
    fh.write('---------- tags ----------\n')
    fh.write('\n'.join(podcasts_tags))
