#!/usr/bin/env python
#coding:utf-8
#Copyright (C) dirlt

HEAD = """
""".replace('\n','')

HEAD = ""

HEAD_END = """
""".replace('\n','')

HEAD_END = ""

BODY = """
""".replace('\n','')

BODY = ""

BODY_END = """
<!-- DISQUS BEGIN -->
<div id="disqus_thread"></div>
<script type="text/javascript">
/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
/* required: replace example with your forum shortname  */
var disqus_shortname = 'dirtysalt';
var disqus_identifier = '%(site_id)s';
var disqus_title = '%(site_title)s';
var disqus_url = 'https://dirtysalt.github.io/html/%(site_id)s';
/* * * DON'T EDIT BELOW THIS LINE * * */
(function() {
var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
<!-- DISQUS END -->
""".replace('\n','')

import glob
import string
import re
r1 = re.compile(r'^<meta name="generated" content="')
r2 = re.compile(r'^<p class="date">Date: ')
r3 = re.compile(r'^<a href="http://validator.w3.org/check')
r4 = re.compile(r'^<!-- \d{4}-\d{2}\-\d{2} ')

filter_words = ('resume',)
HTML_DIR = '../html/'
html_files = glob.glob(HTML_DIR + '*.html') + \
  glob.glob(HTML_DIR + 'blogs/*.html')

for f in html_files:
    skip = False
    for w in filter_words:
        if f.find(w) != -1:
            skip = True
            break
    if skip:
        continue

    xs = open(f).readlines()
    site_id = f[len(HTML_DIR):]
    site_title = site_id

    data=[]
    for x in xs:
        x = x[:-1] # strip trailing \n
        if x.find('<head>') != -1 and not x == '<head>' + HEAD + '\n':
            data.append('<head>' + HEAD)
        elif x.find('<body>') != -1 and not x == '<body>' + BODY + '\n':
            data.append('<body>' + BODY)
        elif x.find('</head>') != -1 and not x == HEAD_END + '</head>' + '\n':
            data.append(HEAD_END + '</head>')
        elif x.find('</body>') != -1 and not x == BODY_END%(locals()) + '</body>' + '\n':
            data.append(BODY_END%(locals()) + '</body>')
        elif r1.match(x) or r2.match(x) or r3.match(x) or r4.match(x):
            pass
        else:
            data.append(x)
        if x.find('<title>') !=-1 and x.find('</title>') != -1:
            site_title = x[len('<title>'):-len('</title>')].replace("'", '')
    print('add code to \'%s\''%(f))
    with open(f, 'w') as fh:
        fh.writelines(map(lambda x: x + '\n', data))


# generate sitemap for indexing
site = 'http://dirtysalt.github.io/html/'
files = glob.glob('*.org') + glob.glob('blogs/*.org')
with open('sitemap.txt', 'w') as fh:
    fh.writelines(map(lambda x: site + x[:-3] + 'html\n', files))
with open('sitemap.xml', 'w') as fh:
    fh.write("""<?xml version="1.0" encoding="UTF-8"?>
    <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    """)
    fh.writelines(map(lambda x: '<url><loc>{}</loc></url>\n'.format(site + x[:-3] + 'html'), files))
    fh.write('</urlset>\n')
